import { CentralAfrica, EasternAfrica, IndianOcean, MiddleWestAfrica, WestAfrica } from "./timezones/Africa"
import { Barbados, EasternGreaterAntilles, LeewardAntilles, LeewardIslands, TrinidadAndTobago, WesternGreaterAntilles, WindwardIslands } from "./timezones/Antilles"
import { Christmas, Cocos, EasternAustralia, LordHoweIsland, NorfolkIsland, NorthernAustralia, Queensland, SouthAustralia, WesternAustralia } from "./timezones/Australia"
import { Acre, BrazilianIslands, EasternBrazil, WesternBrazil } from "./timezones/Brazil"
import { EasternCentralAsia, WesternCentralAsia } from "./timezones/CentralAsia"
import CentralIndonesia from "./timezones/CentralIndonesia"
import China from "./timezones/China"
import EasternIndonesia from "./timezones/EasternIndonesia"
import { CentralEurope, EasternEurope, Mediterranean, WesternEurope, WesternScandinavia } from "./timezones/Europe"
import JapanKorea from "./timezones/JapanKorea"
import { CentralAmerica, CentralSouthAmerica, Colombia, EasterIsland, EasternSouthAmerica } from "./timezones/LatinAmerica"
import { Afghanistan, Arabia, EastArabia, Caucasus, Iran, Levant, Turkey } from "./timezones/MiddleEast"
import { EasternMongolia, WesternMongolia } from "./timezones/Mongolia"
import { Alaska, AleutianIslands, Arizona, AtlanticOcean, Bermuda, Central, Eastern, Hawaii, Mountain, Newfoundland, NorthwesternAtlantic, Pacific, QuintanaRoo, Saskatchewan, WesternGreenland, Yukon } from "./timezones/NorthAmerica"
import NorthAtlantic from "./timezones/NorthAtlantic"
import { AmericanSamoa, Chatham, EasternKiribati, MarquesasIslands, NewZealand, Oceania, PapuaNewGuinea, Samoa, Tonga, WesternOceania } from "./timezones/Oceania"
import { Kaliningrad, Kamchatka, Krasnoyarsk, Irkutsk, Moscow, Omsk, Samara, Srednekolymsk, Vladivostok, Yakutsk, Yekaterinburg } from "./timezones/Russia"
import { Bangladesh, India, Myanmar, Nepal, Pakistan } from "./timezones/SouthAsia"
import { Indochina, Malaysia, Philippines } from "./timezones/SoutheastAsia"
import WesternIndonesia from "./timezones/WesternIndonesia"

export default [
  Acre,
  Afghanistan,
  Alaska,
  AleutianIslands,
  AmericanSamoa,
  Arabia,
  Arizona,
  AtlanticOcean,
  Bangladesh,
  Barbados,
  Bermuda,
  BrazilianIslands,
  Caucasus,
  Central,
  CentralAfrica,
  CentralAmerica,
  CentralEurope,
  CentralIndonesia,
  CentralSouthAmerica,
  Chatham,
  China,
  Christmas,
  Cocos,
  Colombia,
  EastArabia,
  EasterIsland,
  Eastern,
  EasternAfrica,
  EasternAustralia,
  EasternBrazil,
  EasternCentralAsia,
  EasternEurope,
  EasternGreaterAntilles,
  EasternIndonesia,
  EasternKiribati,
  EasternMongolia,
  EasternSouthAmerica,
  Hawaii,
  India,
  IndianOcean,
  Indochina,
  Iran,
  Irkutsk,
  JapanKorea,
  Kaliningrad,
  Kamchatka,
  Krasnoyarsk,
  LeewardAntilles,
  LeewardIslands,
  Levant,
  LordHoweIsland,
  Malaysia,
  MarquesasIslands,
  Mediterranean,
  MiddleWestAfrica,
  Moscow,
  Mountain,
  Myanmar,
  Nepal,
  Newfoundland,
  NewZealand,
  NorfolkIsland,
  NorthAtlantic,
  NorthernAustralia,
  NorthwesternAtlantic,
  Oceania,
  Omsk,
  Pacific,
  Pakistan,
  PapuaNewGuinea,
  Philippines,
  Queensland,
  QuintanaRoo,
  Samara,
  Samoa,
  Saskatchewan,
  Srednekolymsk,
  SouthAustralia,
  Tonga,
  TrinidadAndTobago,
  Turkey,
  Vladivostok,
  WestAfrica,
  WesternAustralia,
  WesternBrazil,
  WesternCentralAsia,
  WesternEurope,
  WesternGreaterAntilles,
  WesternGreenland,
  WesternIndonesia,
  WesternMongolia,
  WesternOceania,
  WesternScandinavia,
  WindwardIslands,
  Yakutsk,
  Yekaterinburg,
  Yukon,
]