import { CaboVerde, CentralAfrica, EasternAfrica, IndianOcean, MiddleWestAfrica, WestAfrica } from "./timezones/Africa"
import { Antilles } from "./timezones/Antilles"
import { EasternAustralia, LordHoweIsland, NorfolkIsland, NorthernAustralia, Queensland, SouthAustralia } from "./timezones/Australia"
import { China, JapanKorea } from "./timezones/EastAsia"
import { CentralEurope, EasternEurope, NorthAtlantic, WesternEurope } from "./timezones/Europe"
import { CentralIndonesia, EasternIndonesia, WesternIndonesia } from "./timezones/Indonesia"
import { BrazilianIslands, CentralAmerica, CentralSouthAmerica, Chile, Colombia, EasternSouthAmerica, Paraguay } from "./timezones/LatinAmerica"
import { Afghanistan, Arabia, Iran, Israel, Jordan, Lebanon, Palestine } from "./timezones/MiddleEast"
import { Alaska, AleutianIslands, Arizona, AtlanticOcean, Central, Cuba, Eastern, Hawaii, Mountain, Newfoundland, NorthwesternAtlantic, Pacific, WesternGreenland } from "./timezones/NorthAmerica"
import { AmericanSamoa, Chatham, EasternKiribati, Fiji, GambierIslands, MarquesasIslands, NewZealand, Oceania, PapuaNewGuinea, Pitcairn, Samoa, Tonga, WesternOceania } from "./timezones/Oceania"
import { Kaliningrad, Kamchatka, Krasnoyarsk, Moscow, Omsk, Samara, Srednekolymsk, Vladivostok, Yekaterinburg } from "./timezones/Russia"
import { Bangladesh, India, Myanmar, Nepal, Pakistan } from "./timezones/SouthAsia"

export default [
  Afghanistan,
  Alaska,
  AleutianIslands,
  AmericanSamoa,
  Antilles,
  Arabia,
  Arizona,
  AtlanticOcean,
  Bangladesh,
  BrazilianIslands,
  CaboVerde,
  Central,
  CentralAfrica,
  CentralAmerica,
  CentralEurope,
  CentralIndonesia,
  CentralSouthAmerica,
  Chatham,
  Chile,
  China,
  Colombia,
  Cuba,
  Eastern,
  EasternAfrica,
  EasternAustralia,
  EasternEurope,
  EasternIndonesia,
  EasternKiribati,
  EasternSouthAmerica,
  Fiji,
  GambierIslands,
  Hawaii,
  India,
  IndianOcean,
  Iran,
  Israel,
  JapanKorea,
  Jordan,
  Kaliningrad,
  Kamchatka,
  Krasnoyarsk,
  Lebanon,
  LordHoweIsland,
  MarquesasIslands,
  MiddleWestAfrica,
  Moscow,
  Mountain,
  Myanmar,
  Nepal,
  Newfoundland,
  NewZealand,
  NorfolkIsland,
  NorthAtlantic,
  NorthernAustralia,
  NorthwesternAtlantic,
  Oceania,
  Omsk,
  Pacific,
  Pakistan,
  Palestine,
  PapuaNewGuinea,
  Paraguay,
  Pitcairn,
  Queensland,
  Samara,
  Samoa,
  Srednekolymsk,
  SouthAustralia,
  Tonga,
  Vladivostok,
  WestAfrica,
  WesternEurope,
  WesternGreenland,
  WesternIndonesia,
  WesternOceania,
  Yekaterinburg,
]